CREATE TABLE IF NOT EXISTS queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    path TEXT NOT NULL,
    filename TEXT UNIQUE NOT NULL,
    transcode TEXT DEFAULT "N" NOT NULL,
    status TEXT DEFAULT "skipped" NOT NULL
);