CREATE TABLE IF NOT EXISTS queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    path TEXT NOT NULL,
    filename TEXT UNIQUE NOT NULL,
    convert TEXT DEFAULT "skip" NOT NULL,
    status TEXT DEFAULT "skip" NOT NULL
);